/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import crud.gal.AddEvent;
import crud.gal.Automabile;
import crud.gal.CrudAutoma;
import crud.gal.RicercaEvent;

/**
 *
 * @author Federico
 */
public class CrudUI extends javax.swing.JFrame implements Automabile {

    CrudAutoma automa;

    public CrudUI() {
        initComponents();
        automa = new CrudAutoma(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDescrizione = new javax.swing.JTextField();
        jTextFieldCodice = new javax.swing.JTextField();
        jButtonModifica = new javax.swing.JButton();
        jButtonAnnulla = new javax.swing.JButton();
        jButtonRimuovi = new javax.swing.JButton();
        jButtonNuova = new javax.swing.JButton();
        jButtonConferma = new javax.swing.JButton();
        jTextFieldCercaPerCodice = new javax.swing.JTextField();
        jButtonCerca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldDescrizione.setText("Descrizione");

        jTextFieldCodice.setText("Codice");
        jTextFieldCodice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodiceActionPerformed(evt);
            }
        });

        jButtonModifica.setText("Modifica");

        jButtonAnnulla.setText("Annulla");
        jButtonAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnullaActionPerformed(evt);
            }
        });

        jButtonRimuovi.setText("Rimuovi");

        jButtonNuova.setText("Nuova");
        jButtonNuova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuovaActionPerformed(evt);
            }
        });

        jButtonConferma.setText("Conferma");

        jTextFieldCercaPerCodice.setText("Cerca per Codice");

        jButtonCerca.setText("Cerca");
        jButtonCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCercaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jTextFieldDescrizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModifica)
                            .addComponent(jTextFieldCercaPerCodice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonConferma)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAnnulla))
                            .addComponent(jButtonCerca))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuova)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRimuovi)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jTextFieldCodice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(516, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescrizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuova))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifica)
                    .addComponent(jButtonAnnulla)
                    .addComponent(jButtonRimuovi)
                    .addComponent(jButtonConferma))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCercaPerCodice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCerca))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jTextFieldCodice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(418, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodiceActionPerformed

    private void jButtonNuovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuovaActionPerformed
        automa.next(new AddEvent());
    }//GEN-LAST:event_jButtonNuovaActionPerformed

    private void jButtonCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCercaActionPerformed
        automa.next(new RicercaEvent());
    }//GEN-LAST:event_jButtonCercaActionPerformed

    private void jButtonAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnullaActionPerformed
        automa.next(new RicercaEvent());
    }//GEN-LAST:event_jButtonAnnullaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulla;
    private javax.swing.JButton jButtonCerca;
    private javax.swing.JButton jButtonConferma;
    private javax.swing.JButton jButtonModifica;
    private javax.swing.JButton jButtonNuova;
    private javax.swing.JButton jButtonRimuovi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCercaPerCodice;
    private javax.swing.JTextField jTextFieldCodice;
    private javax.swing.JTextField jTextFieldDescrizione;
    // End of variables declaration//GEN-END:variables

    @Override
    public void statoIniziale() {
        jTextFieldCodice.setVisible(false);
        jButtonNuova.setVisible(true);
        jButtonCerca.setVisible(true);
        jTextFieldCercaPerCodice.setVisible(true);
        jButtonAnnulla.setVisible(false);
        jButtonConferma.setVisible(false);
        jButtonModifica.setVisible(false);
        jTable1.setVisible(true);
        jTextFieldDescrizione.setVisible(false);  
        jButtonRimuovi.setVisible(false);          
    }

    @Override
    public void entraStatoRicerca() {
        jTextFieldCodice.setVisible(false);
        jButtonNuova.setVisible(true);
        jButtonCerca.setVisible(true);
        jTextFieldCercaPerCodice.setVisible(true);
        jButtonAnnulla.setVisible(false);
        jButtonConferma.setVisible(false);
        jButtonModifica.setVisible(false);
        jTable1.setVisible(false);
        jTextFieldDescrizione.setVisible(false);  
        jButtonRimuovi.setVisible(false);      
    }

    @Override
    public void entraStatoRimuovi() {
        jTextFieldCodice.setVisible(true);
        jButtonNuova.setVisible(false);
        jButtonCerca.setVisible(false);
        jTextFieldCercaPerCodice.setVisible(false);
        jButtonAnnulla.setVisible(true);
        jButtonConferma.setVisible(true);
        jButtonModifica.setVisible(false);
        jTable1.setVisible(false);
        jTextFieldDescrizione.setVisible(true);  
        jButtonRimuovi.setVisible(false);
    }

    @Override
    public void entraStatoModifica() {
        jTextFieldCodice.setVisible(true);
        jButtonNuova.setVisible(false);
        jButtonCerca.setVisible(false);
        jTextFieldCercaPerCodice.setVisible(false);
        jButtonAnnulla.setVisible(true);
        jButtonConferma.setVisible(true);
        jButtonModifica.setVisible(false);
        jTable1.setVisible(false);
        jTextFieldDescrizione.setVisible(true);  
        jButtonRimuovi.setVisible(false);    }

    @Override
    public void entraStatoVisualizza() {
        jTextFieldCodice.setVisible(true);
        jButtonNuova.setVisible(true);
        jButtonCerca.setVisible(true);
        jTextFieldCercaPerCodice.setVisible(true);
        jButtonAnnulla.setVisible(false);
        jButtonConferma.setVisible(false);
        jButtonModifica.setVisible(true);
        jTable1.setVisible(true);
        jTextFieldDescrizione.setVisible(true);  
        jButtonRimuovi.setVisible(true);   
    }

    @Override
    public void entraStatoAggiungi() {
        jTextFieldCodice.setVisible(true);
        jButtonNuova.setVisible(false);
        jButtonCerca.setVisible(false);
        jTextFieldCercaPerCodice.setVisible(false);
        jButtonAnnulla.setVisible(true);
        jButtonConferma.setVisible(true);
        jButtonModifica.setVisible(false);
        jTable1.setVisible(false);
        jTextFieldDescrizione.setVisible(true);  
        jButtonRimuovi.setVisible(false);    
    }
}
